# Generated by Django 4.2 on 2025-12-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_roadmapitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapitem',
            name='step_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
