# Generated by Django 4.2 on 2025-12-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_roadmapitem_step_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapitem',
            name='source',
            field=models.CharField(choices=[('ai-generated', 'AI Generated'), ('user-added', 'User Added'), ('roadmap-sh', 'Roadmap.sh')], default='user-added', max_length=20),
        ),
    ]
